Skillberto\SonataPageMenuBundle\Entity\Menu:
  type: entity
  table: skillberto_menu
  repositoryClass: Skillberto\SonataPageMenuBundle\Entity\Repository\MenuRepository
  gedmo:
    tree:
      type: nested
  id:
    id:
      type: integer
      column: id
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    clickable:
      type: boolean
      nullable: true
    lft:
      type: integer
      gedmo:
        - treeLeft
    rgt:
      type: integer
      gedmo:
        - treeRight
    root:
      type: integer
      nullable: true
      gedmo:
        - treeRoot
    lvl:
      type: integer
      gedmo:
        - treeLevel
    attributes:
      type: array
    active:
      type: boolean
    createdAt:
      type: datetime
    updatedAt:
      type: datetime

  manyToOne:
    page:
      targetEntity: Application\Sonata\PageBundle\Entity\Page
      joinColumn:
        name: page_id
        referencedColumnName: id
      nullable: true

    site:
      targetEntity: Application\Sonata\PageBundle\Entity\Site
      joinColumn:
        name: site_id
        referencedColumnName: id

    parent:
      targetEntity: Skillberto\SonataPageMenuBundle\Entity\Menu
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
       - treeParent
      # - sortableGroup

  oneToMany:
    children:
      cascade: [persist]
      targetEntity: Skillberto\SonataPageMenuBundle\Entity\Menu
      mappedBy: parent
      orderBy:
        lft: ASC

  lifecycleCallbacks:
    prePersist: [ createdAt ]
    postPersist: [ updateAt ]